export const moviesData = [
    {
      id: Math.random(),
      image: 'https://fr.web.img3.acsta.net/pictures/15/11/10/09/30/165611.jpg',
      rating: 5,
      name: 'THE REVENANT',
      date: '2015', 
      description:'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.',
    },
    {
      id: Math.random(),
      image: 'https://fr.web.img6.acsta.net/pictures/20/03/31/09/22/0259222.jpg',
      rating: 4,
      name: 'Extraction',
      date: '2020',
      description:'Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he is enlisted to rescue the kidnapped son of an imprisoned international crime lord.',
    },
    {
      id: Math.random(),
      image: 'https://fr.web.img6.acsta.net/pictures/19/11/22/09/44/3027567.jpg',
      rating: 3,
      name: 'Bad Boys for Life',
      date: '2020',
      description:'Miami detectives Mike Lowrey and Marcus Burnett must face off against a mother-and-son pair of drug lords who wreak vengeful havoc on their city.',
    },
    {
      id: Math.random(),
      image: 'https://media.senscritique.com/media/000018269542/source_big/Siberia.jpg',
      rating: 3,
      name: 'Siberia',
      date: '2018',
      description:'When an American diamond trader is Russian partner goes missing, he journeys to Siberia in search of him, but instead begins a love affair.',
    },
    {
      id: Math.random(),
      image:'https://fr.web.img5.acsta.net/c_215_290/pictures/16/02/16/16/52/211080.jpg',
      rating: 5,
      name: 'ROOM',
      date: '2015',
      description:'Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.',
    },
      {
       id: Math.random(),
       image:'https://fr.web.img6.acsta.net/pictures/14/08/14/15/34/168977.jpg',
       rating: 4,
       name: 'The Giver',
       date: '2014',
       description:'In a seemingly perfect community, without war, pain, suffering, differences or choice, a young boy is chosen to learn from an elderly man about the true pain and pleasure of the "real" world.',
     }, 
     {
      id: Math.random(),
      image:'https://fr.web.img4.acsta.net/pictures/17/01/19/16/02/513278.jpg',
      rating: 4,
      name: 'LOGAN',
      date: '2017',
      description:'In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.',
    },
   
  ];